server:
  port: 8081

spring:
  application:
    name: item-service

  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    # 过期时间
    lease-expiration-duration-in-seconds: 15
    # 心跳时间
    lease-renewal-interval-in-seconds: 5


mybatis:
  type-aliases-package: com.leyou.item.pojo